# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 - main

pool:
 vmImage: ubuntu-latest 

stages:
  - stage: 
    jobs:
    - job: 
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            sudo apt-get install wget apt-transport-https gnupg lsb-release
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
            echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
            sudo apt-get update
            sudo apt-get install trivy
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'trivy repo --quiet --severity CRITICAL https://github.com/CAESAR269/spring-petclinic.git --format JSON'
