# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'caesar269 / chatgpt'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(977812bc-0cfb-4c57-8912-a7804ccf8fba)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'kube.sh'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      kubectl apply -f chatgpt-clone-deploy.yaml
      kubectl get svc