# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 - main

pool:
 vmImage: ubuntu-latest 

stages:
  - stage: 
    jobs:
    - job: 
      steps:
      - task: Kubernetes@1
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: 'Dev-sample_cluster-dev-1707228159481'
          command: 'apply'
          useConfigurationFile: true
          configurationType: 'inline'
          inline: |
            kubectl apply -f ./kube/chatgpt-clone-deploy.yaml
            
            kubectl apply -f ./kube/chatgpt-clone-svc.yaml
