name: "Docker Build"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name : Docker build
        run: |
          docker build -t caesar269/chatgpt:latest ./
