name: "Docker Build"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name : Docker build
        run: |
          docker build -t CAESAR269/chatgpt:latest .
          docker login -u CAESAR269 -p Udai@1248
          docker push chatgpt:latest
